<?php

namespace App\Console\Commands;

use App\Models\SeniorCitizen;
use Carbon\Carbon;
use Illuminate\Console\Command;
use PhpOffice\PhpSpreadsheet\IOFactory;

/**
 * Non-destructive demographic backfill for the existing 360 senior records.
 *
 * Root cause: osca_normalized.csv (generated by export_normalized_db.py) omits
 * 8 columns; MagdapioImportSeeder hard-codes those fields to null. As a result,
 * every senior seeded from the normalized CSV shows N/A for demographics even
 * though the data exists in the original source files.
 *
 * This command reads osca.csv (290-row bulk cohort) and magdapio_cleaned.xlsx
 * (70-row survey batch), matches each source row to an existing SeniorCitizen
 * by first_name + last_name + date_of_birth + barangay, then fills only the
 * currently-blank fields.  It never re-seeds, never overwrites existing data,
 * and never touches ML predictions.
 *
 * Writes go through Eloquent so the EncryptedOrPlainText cast on contact_number
 * and place_of_birth is respected.
 *
 * Usage:
 *   php artisan seniors:backfill-demographics --dry-run   # preview counts only
 *   php artisan seniors:backfill-demographics             # apply changes
 */
class BackfillSeniorDemographics extends Command
{
    protected $signature = 'seniors:backfill-demographics
                            {--dry-run : Preview changes without writing to the database}';

    protected $description = 'Backfill place_of_birth, religion, blood_type, contact_number and consent '
        .'from osca.csv / magdapio_cleaned.xlsx into existing senior records (non-destructive).';

    /** @var array<string,SeniorCitizen> match-key → loaded model */
    private array $lookup = [];

    private array $stats = [
        'matched' => 0,
        'unmatched' => 0,
        'place_of_birth' => 0,
        'religion' => 0,
        'blood_type' => 0,
        'contact_number' => 0,
        'consent' => 0,
        'saved' => 0,
    ];

    public function handle(): int
    {
        $dryRun = (bool) $this->option('dry-run');

        if ($dryRun) {
            $this->info('[DRY RUN] No data will be written to the database.');
        }

        // ── Locate source files ──────────────────────────────────────────────
        $csvPath = file_exists(base_path('osca.csv'))
            ? base_path('osca.csv')
            : base_path('../osca.csv');

        $xlsxPath = file_exists(base_path('../magdapio_cleaned.xlsx'))
            ? base_path('../magdapio_cleaned.xlsx')
            : base_path('magdapio_cleaned.xlsx');

        if (! file_exists($csvPath)) {
            $this->error('osca.csv not found. Tried: '.base_path('osca.csv').' and '.base_path('../osca.csv'));

            return self::FAILURE;
        }
        if (! file_exists($xlsxPath)) {
            $this->error('magdapio_cleaned.xlsx not found. Tried: '.base_path('../magdapio_cleaned.xlsx').' and '.base_path('magdapio_cleaned.xlsx'));

            return self::FAILURE;
        }

        // ── Build match-key → model lookup (Eloquent, so encrypted casts apply) ──
        $this->info('Loading seniors from database...');
        SeniorCitizen::whereNull('deleted_at')->chunk(200, function ($chunk) {
            foreach ($chunk as $senior) {
                $key = $this->matchKey(
                    $senior->first_name,
                    $senior->last_name,
                    $senior->date_of_birth?->format('Y-m-d'),
                    $senior->barangay,
                );
                $this->lookup[$key] = $senior;
            }
        });
        $this->info('  '.count($this->lookup).' seniors loaded.');
        $this->info('');

        // ── Process osca.csv ─────────────────────────────────────────────────
        $this->info('Processing osca.csv...');
        foreach ($this->parseCsvRows($csvPath) as $row) {
            $this->processSourceRow($row, $dryRun);
        }

        // ── Process magdapio_cleaned.xlsx ────────────────────────────────────
        $this->info('Processing magdapio_cleaned.xlsx...');
        foreach ($this->parseXlsxRows($xlsxPath) as $row) {
            $this->processSourceRow($row, $dryRun);
        }

        // ── Summary (aggregate only — RA 10173) ──────────────────────────────
        $this->info('');
        $this->info('=== Backfill '.($dryRun ? 'DRY RUN ' : '').'Complete ===');
        $this->table(
            ['Metric', 'Count'],
            [
                ['Source rows matched in DB',                                      $this->stats['matched']],
                ['Source rows NOT matched (name / DOB / barangay mismatch)',       $this->stats['unmatched']],
                ['Records '.($dryRun ? 'that would be saved' : 'saved'),          $this->stats['saved']],
                ['  ↳ place_of_birth filled',                                      $this->stats['place_of_birth']],
                ['  ↳ religion filled',                                             $this->stats['religion']],
                ['  ↳ blood_type filled',                                           $this->stats['blood_type']],
                ['  ↳ contact_number filled',                                       $this->stats['contact_number']],
                ['  ↳ consent_given_at filled',                                     $this->stats['consent']],
            ]
        );

        if ($dryRun) {
            $this->line('');
            $this->line('Run without --dry-run to apply these changes.');
        }

        return self::SUCCESS;
    }

    // ── Source parsers ────────────────────────────────────────────────────────

    /**
     * Read osca.csv (machine headers) and return normalized source rows.
     *
     * @return array<int, array{first_name:?string, last_name:?string, barangay:?string,
     *                           dob:?string, place_of_birth:?string, religion:?string,
     *                           blood_type:?string, contact:?string, consent:?string, timestamp_str:?string}>
     */
    private function parseCsvRows(string $path): array
    {
        $fp = fopen($path, 'r');
        if (! $fp) {
            $this->error("Cannot open {$path}");

            return [];
        }

        // Strip UTF-8 BOM
        $firstBytes = fread($fp, 3);
        if ($firstBytes !== "\xef\xbb\xbf") {
            rewind($fp);
        }

        $header = fgetcsv($fp);
        if (! $header) {
            fclose($fp);

            return [];
        }
        if (str_starts_with($header[0], "\xef\xbb\xbf")) {
            $header[0] = substr($header[0], 3);
        }

        $rows = [];
        while (($line = fgetcsv($fp)) !== false) {
            $raw = $this->rowToAssoc($header, $line);
            $rows[] = [
                'first_name' => $this->strVal($raw['first_name'] ?? null),
                'last_name' => $this->strVal($raw['last_name'] ?? null),
                'barangay' => $this->strVal($raw['barangay'] ?? null),
                'dob' => $this->strVal($raw['dob'] ?? null),
                'place_of_birth' => $this->strVal($raw['place_of_birth'] ?? null),
                'religion' => $this->strVal($raw['religion'] ?? null),
                'blood_type' => $this->strVal($raw['blood_type'] ?? null),
                'contact' => $this->strVal($raw['contact_number'] ?? null),
                'consent' => $this->strVal($raw['consent'] ?? null),
                'timestamp_str' => $this->strVal($raw['timestamp'] ?? null),
            ];
        }
        fclose($fp);

        return $rows;
    }

    /**
     * Read magdapio_cleaned.xlsx "Cleaned Data" sheet and return normalized source rows.
     *
     * @return array<int, array{first_name:?string, last_name:?string, barangay:?string,
     *                           dob:?string, place_of_birth:?string, religion:?string,
     *                           blood_type:?string, contact:?string, consent:?string, timestamp_str:?string}>
     */
    private function parseXlsxRows(string $path): array
    {
        if (! class_exists(IOFactory::class)) {
            $this->error('PhpSpreadsheet is not installed. Run: composer require phpoffice/phpspreadsheet');

            return [];
        }

        $spreadsheet = IOFactory::load($path);

        // Prefer the "Cleaned Data" sheet; fall back to the active sheet
        $sheet = null;
        foreach ($spreadsheet->getAllSheets() as $s) {
            if ($s->getTitle() === 'Cleaned Data') {
                $sheet = $s;
                break;
            }
        }
        if ($sheet === null) {
            $this->warn('Sheet "Cleaned Data" not found; using active sheet instead.');
            $sheet = $spreadsheet->getActiveSheet();
        }

        $allRows = $sheet->toArray(null, true, true, false);
        if (empty($allRows)) {
            return [];
        }

        $header = array_map(fn ($h) => trim((string) $h), array_shift($allRows));

        $rows = [];
        foreach ($allRows as $line) {
            // Skip trailing blank rows produced by Excel
            if (empty(array_filter(array_map(fn ($v) => trim((string) $v), $line)))) {
                continue;
            }
            $raw = $this->rowToAssoc($header, $line);
            $rows[] = [
                'first_name' => $this->strVal($raw['First Name'] ?? null),
                'last_name' => $this->strVal($raw['Last Name'] ?? null),
                'barangay' => $this->strVal($raw['Address (Barangay)'] ?? null),
                'dob' => $this->strVal($raw['Date of Birth'] ?? null),
                'place_of_birth' => $this->strVal($raw['Place of Birth'] ?? null),
                'religion' => $this->strVal($raw['Religion'] ?? null),
                'blood_type' => $this->strVal($raw['Blood Type'] ?? null),
                'contact' => $this->strVal($raw['Contact Number'] ?? null),
                'consent' => $this->strVal($raw['Consent'] ?? null),
                'timestamp_str' => $this->strVal($raw['Timestamp'] ?? null),
            ];
        }

        return $rows;
    }

    // ── Core backfill logic ───────────────────────────────────────────────────

    /**
     * Match one normalized source row to a DB record and fill blank demographic fields.
     *
     * Only aggregate counts are logged; no individual PII is printed.
     */
    private function processSourceRow(array $row, bool $dryRun): void
    {
        $firstName = $row['first_name'] ?? null;
        $lastName = $row['last_name'] ?? null;
        $barangay = $row['barangay'] ?? null;

        if (! $firstName || ! $lastName || ! $barangay) {
            return;
        }

        $parsedDob = $this->parseDate($row['dob'] ?? null, dobMode: true);
        if (! $parsedDob) {
            return;
        }

        $key = $this->matchKey($firstName, $lastName, $parsedDob, $barangay);
        if (! isset($this->lookup[$key])) {
            $this->stats['unmatched']++;

            return;
        }

        $this->stats['matched']++;
        $senior = $this->lookup[$key];
        $dirty = false;
        $wouldChange = false;

        // Fill blank demographics from source
        if (blank($senior->place_of_birth) && ! blank($row['place_of_birth'])) {
            $this->stats['place_of_birth']++;
            $wouldChange = true;
            if (! $dryRun) {
                $senior->place_of_birth = $row['place_of_birth'];
                $dirty = true;
            }
        }
        if (blank($senior->religion) && ! blank($row['religion'])) {
            $this->stats['religion']++;
            $wouldChange = true;
            if (! $dryRun) {
                $senior->religion = $row['religion'];
                $dirty = true;
            }
        }
        if (blank($senior->blood_type) && ! blank($row['blood_type'])) {
            $this->stats['blood_type']++;
            $wouldChange = true;
            if (! $dryRun) {
                $senior->blood_type = $row['blood_type'];
                $dirty = true;
            }
        }
        if (blank($senior->contact_number) && ! blank($row['contact'])) {
            $this->stats['contact_number']++;
            $wouldChange = true;
            if (! $dryRun) {
                $senior->contact_number = $row['contact'];
                $dirty = true;
            }
        }

        // Consent: set consent_given_at from the form timestamp when source says consent was given
        $consentVal = strtolower(trim((string) ($row['consent'] ?? '')));
        if (! $senior->consent_given_at && in_array($consentVal, ['yes', '1', 'true', 'y'], true)) {
            $this->stats['consent']++;
            $wouldChange = true;
            if (! $dryRun) {
                $consentAt = $this->parseDateTime($row['timestamp_str'] ?? null);
                $senior->consent_given_at = $consentAt ?? $senior->created_at;
                $senior->consent_method = 'Imported (survey form)';
                $dirty = true;
            }
        }

        if (! $dryRun && $dirty) {
            $senior->save();
            $this->stats['saved']++;
        } elseif ($dryRun && $wouldChange) {
            $this->stats['saved']++;
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Build a deterministic match key from name + DOB + barangay (case-insensitive, trimmed).
     *
     * Uses \x00 as delimiter (guaranteed not to appear in a name or barangay).
     */
    private function matchKey(string $firstName, string $lastName, ?string $dob, string $barangay): string
    {
        return implode("\x00", [
            strtolower(trim($firstName)),
            strtolower(trim($lastName)),
            $dob ?? '',
            strtolower(trim($barangay)),
        ]);
    }

    /** Build an associative array from parallel header + line arrays (trims header keys). */
    private function rowToAssoc(array $header, array $line): array
    {
        $assoc = [];
        foreach ($header as $idx => $key) {
            $assoc[trim((string) $key)] = $line[$idx] ?? null;
        }

        return $assoc;
    }

    /** Return trimmed string or null; treats empty string and 'nan' as null. */
    private function strVal(mixed $value): ?string
    {
        if ($value === null) {
            return null;
        }
        $v = trim((string) $value);
        if ($v === '' || strtolower($v) === 'nan') {
            return null;
        }

        return $v;
    }

    /**
     * Parse a date string into Y-m-d format.
     *
     * @param  bool  $dobMode  When true, a value with a time suffix is treated as a
     *                         Google-Form date-picker export in Philippine locale (d/m/Y).
     */
    private function parseDate(mixed $value, bool $dobMode = false): ?string
    {
        $v = $this->strVal($value);
        if ($v === null) {
            return null;
        }

        // Philippine locale ambiguity: Google Form date-picker exports d/m/Y H:i
        $hasSlashDate = preg_match('/^(\d{1,2})\/(\d{1,2})\/(\d{4})/', $v, $m);
        if ($hasSlashDate) {
            $dateOnly = "{$m[1]}/{$m[2]}/{$m[3]}";
            $hasTimeSuffix = (bool) preg_match('/\s+\d/', $v);
            if ((int) $m[1] > 12) {
                // Day-first unambiguous
                try {
                    return Carbon::createFromFormat('d/m/Y', $dateOnly)->format('Y-m-d');
                } catch (\Throwable) {
                }
            } elseif ($dobMode && $hasTimeSuffix) {
                // DOB from Google Form date-picker: Philippine locale
                try {
                    return Carbon::createFromFormat('d/m/Y', $dateOnly)->format('Y-m-d');
                } catch (\Throwable) {
                }
            }
        }

        $formats = ['m/d/Y H:i:s', 'm/d/Y H:i', 'm/d/Y', 'Y-m-d', 'd/m/Y'];
        foreach ($formats as $fmt) {
            try {
                return Carbon::createFromFormat($fmt, $v)->format('Y-m-d');
            } catch (\Throwable) {
            }
        }

        try {
            return Carbon::parse($v)->format('Y-m-d');
        } catch (\Throwable) {
            return null;
        }
    }

    /**
     * Parse a timestamp string into a Carbon datetime (for consent_given_at).
     * Returns null if the string cannot be parsed.
     */
    private function parseDateTime(?string $value): ?Carbon
    {
        $v = $this->strVal($value);
        if ($v === null) {
            return null;
        }

        $formats = ['m/d/Y H:i:s', 'm/d/Y H:i', 'm/d/Y', 'Y-m-d H:i:s', 'Y-m-d'];
        foreach ($formats as $fmt) {
            try {
                return Carbon::createFromFormat($fmt, $v);
            } catch (\Throwable) {
            }
        }

        try {
            return Carbon::parse($v);
        } catch (\Throwable) {
            return null;
        }
    }
}
