<?php

namespace App\Observers;

use App\Models\MlResult;
use App\Models\SeniorCitizen;
use App\Support\SeniorDataVersion;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Cache;

/**
 * Keeps barangay-derived state in sync when a senior's barangay is edited.
 *
 * Barangay drives several things that otherwise never get refreshed on a
 * plain profile edit: the senior's map coordinates (generated by gis:geocode
 * from the barangay polygon), the accessibility/route-distance data computed
 * from those coordinates, the GIS/dashboard version-stamped caches, and the
 * cached ML risk snapshot. None of those are touched by
 * ProfileSurvey::save() — this observer closes that gap.
 *
 * Deliberately does NOT touch osca_id. The OSCA-ID is a permanent
 * registration number (see SeniorCitizen::generateOscaId()); its prefix
 * reflects the barangay at original registration and is not reissued when a
 * senior later moves. The current barangay is always available from the
 * live `barangay` column, shown separately in the UI.
 */
class SeniorLocationObserver
{
    public function updated(SeniorCitizen $senior): void
    {
        if (! $senior->wasChanged('barangay')) {
            return;
        }

        // A field-verified pin (manual entry or GPS capture) is ground truth
        // about where the senior actually lives, independent of what the
        // barangay text field says — don't discard it. Small pure duplicate
        // of GeocodeSeniors::isVerifiedCoordinate() / CoordinatePrivacy's
        // copy, matching this codebase's existing pattern of not sharing
        // this specific check across classes.
        if ($this->isVerifiedCoordinate($senior)) {
            return;
        }

        // Drop the now-stale generated coordinates. gis:geocode only fills
        // in seniors that are missing coordinates, so nulling here is what
        // makes the senior eligible to be re-geocoded under the *new*
        // barangay instead of silently keeping the old barangay's pin.
        $senior->forceFill([
            'latitude' => null,
            'longitude' => null,
            'location_source' => null,
            'location_accuracy' => null,
            'location_verified_at' => null,
        ])->saveQuietly();

        // The cached ML risk snapshot was computed with the old barangay as
        // an input; treat this the same as any other profile-relevant edit
        // so the "results may be outdated" banner shows and non-forced reuse
        // recomputes instead of silently reusing stale output.
        MlResult::where('senior_citizen_id', $senior->id)
            ->orderByDesc('id')
            ->first()
            ?->markStale('senior_profile_updated');

        // Bump the version stamp folded into GIS/dashboard cache keys so
        // those views don't wait out their TTL to notice the move.
        SeniorDataVersion::bump();
        Cache::forget('gis.seniors_geojson.full');
        Cache::forget('gis.seniors_geojson.generalized');

        // Re-geocode just this senior. Because their coordinates were just
        // nulled, gis:geocode picks them up (it skips seniors that already
        // have coordinates), and its own auto-chain refreshes accessibility
        // scoring inline and queues the ORS route-distance recompute.
        Artisan::queue('gis:geocode', ['--barangay' => $senior->barangay]);
    }

    private function isVerifiedCoordinate(SeniorCitizen $senior): bool
    {
        $source = strtolower((string) $senior->location_source);
        $accuracy = strtolower((string) $senior->location_accuracy);

        return in_array($source, ['manual_pin', 'gps_capture'], true)
            || str_contains($accuracy, 'verified')
            || str_contains($accuracy, 'manual');
    }
}
