@extends('layouts.app')
@section('page-title', 'Recommendations')
@section('page-subtitle', $senior->full_name . ' · ' . $senior->barangay)

@section('content')
<div class="space-y-5">
    <x-breadcrumb :links="[
        ['label' => 'Dashboard', 'href' => route('dashboard')],
        ['label' => 'Senior Records', 'href' => route('seniors.index')],
        ['label' => $senior->full_name, 'href' => route('seniors.show', $senior)],
        ['label' => 'Recommendations'],
    ]" />
    <x-page-header
        eyebrow="Recommendations"
        :title="$senior->full_name"
        :subtitle="$senior->barangay . ' · ' . $recommendations->count() . ' recommendation' . ($recommendations->count() !== 1 ? 's' : '')"
    />
    <div class="flex items-center gap-3">
        <a href="{{ route('recommendations.index') }}" class="btn btn-ghost gap-1.5 pl-1.5">
            <x-heroicon-o-arrow-left class="w-3.5 h-3.5" /> Recommendations list
        </a>
        <a href="{{ route('seniors.show', $senior) }}" class="btn btn-ghost gap-1.5">
            <x-heroicon-o-user class="w-3.5 h-3.5" /> Back to profile
        </a>
    </div>

    {{-- Critical-priority banner (CRITICAL handled as HIGH with critical_priority_flag) --}}
    @if ($senior->latestMlResult?->critical_flag)
    <div class="flex items-start gap-3 bg-high-50 dark:bg-high-50/10 border border-high-100 dark:border-high-700/30 rounded-xl px-4 py-3">
        <x-heroicon-o-exclamation-triangle class="w-4 h-4 text-high-600 dark:text-high-400 flex-shrink-0 mt-0.5" />
        <p class="text-[12px] text-high-700 dark:text-high-300">
            <strong>Critical-priority flag.</strong> This senior's indicators reached the critical threshold. The risk level is reported as <strong>HIGH</strong> under the 3-level system, with a critical-priority flag for immediate OSCA/RHU/MSWDO coordination.
        </p>
    </div>
    @endif

    {{-- Decision-support disclaimer --}}
    <div class="flex items-start gap-3 bg-info-50 dark:bg-info-50/10 border border-info-100 dark:border-info-700/30 rounded-xl px-4 py-3">
        <x-heroicon-o-information-circle class="w-4 h-4 text-info-600 dark:text-info-400 flex-shrink-0 mt-0.5" />
        <p class="text-[12px] text-info-700 dark:text-info-300">
            <strong>Decision-support output.</strong> These recommendations are generated by the AgeSense analytical model based on WHO Healthy Ageing indicators. They are intended to assist OSCA staff — not replace professional assessment or clinical judgment.
        </p>
    </div>

    @php
    $grouped = $recommendations->groupBy('category');
    $catLabels = [
        'health'        => 'Health',
        'financial'     => 'Financial',
        'livelihood'    => 'Livelihood',
        'social'        => 'Social',
        'mental_health' => 'Mental Health',
        'functional'    => 'Functional',
        'hc_access'     => 'Healthcare Access',
        'healthcare_access' => 'Healthcare Access',
        'general'       => 'General',
    ];
    @endphp

    @forelse ($grouped as $category => $recs)
    <div class="card overflow-hidden">
        <div class="card-head">
            <div class="card-title">{{ $catLabels[$category] ?? ucwords(str_replace('_',' ', $category)) }}</div>
            <span class="badge badge-neutral">{{ $recs->count() }} action{{ $recs->count() !== 1 ? 's' : '' }}</span>
        </div>
        <div class="divide-y divide-paper-rule">
            @foreach ($recs->sortBy('priority') as $rec)
            <div class="px-5 py-4 flex items-start gap-3">
                <span class="flex-shrink-0 w-6 h-6 rounded-md grid place-items-center text-[11px] font-bold mt-0.5
                    {{ match($rec->urgency) {
                        'urgent'  => 'bg-high-100 text-high-700',
                        'planned' => 'bg-info-100 text-info-700',
                        default   => 'bg-paper-2 text-ink-500',
                    } }}">{{ $rec->priority }}</span>
                <div class="flex-1 min-w-0">
                    {{-- Recommendation code + WHO domain badges --}}
                    <div class="flex items-center gap-1.5 mb-1 flex-wrap">
                        @if ($rec->recommendation_code)
                        <span class="inline-block text-[10px] font-mono font-semibold px-1.5 py-0.5 rounded bg-paper-2 text-ink-500">
                            {{ $rec->recommendation_code }}
                        </span>
                        @endif
                        @if ($rec->domain)
                        <span class="inline-block text-[10px] font-medium px-1.5 py-0.5 rounded bg-info-50 dark:bg-info-50/10 text-info-700 dark:text-info-300 border border-info-100 dark:border-info-700/30">
                            {{ $rec->domain }}
                        </span>
                        @endif
                    </div>

                    <p class="text-[13px] text-ink-800 leading-relaxed">{{ $rec->action }}</p>

                    {{-- Trigger summary: what flagged this recommendation --}}
                    @if ($rec->trigger_summary)
                    <p class="text-[11.5px] text-ink-500 mt-1.5 flex items-start gap-1">
                        <x-heroicon-o-bolt class="w-3.5 h-3.5 flex-shrink-0 mt-0.5 text-ink-400" />
                        <span><span class="font-medium text-ink-600">Trigger:</span> {{ $rec->trigger_summary }}</span>
                    </p>
                    @endif

                    {{-- Service provider --}}
                    @if ($rec->service_provider)
                    <p class="text-[11.5px] text-ink-500 mt-1.5 flex items-start gap-1">
                        <x-heroicon-o-building-office-2 class="w-3.5 h-3.5 flex-shrink-0 mt-0.5 text-ink-400" />
                        <span>{{ $rec->service_provider }}</span>
                    </p>
                    @endif

                    {{-- Evidence source + APA citation --}}
                    @if ($rec->evidence_source)
                    <p class="text-[11px] text-ink-400 mt-0.5 flex items-start gap-1">
                        <x-heroicon-o-document-text class="w-3 h-3 flex-shrink-0 mt-0.5" />
                        <span class="italic">{{ $rec->evidence_source }}</span>
                        @if ($rec->source_type)
                        <span class="not-italic text-ink-300">· {{ $rec->source_type }}</span>
                        @endif
                    </p>
                    @endif
                    @if ($rec->apa_reference)
                    <p class="text-[10.5px] text-ink-400 mt-0.5 pl-4 italic">{{ $rec->apa_reference }}</p>
                    @endif

                    {{-- Urgency / risk / target date row --}}
                    <div class="flex items-center gap-3 mt-1.5 flex-wrap">
                        @if ($rec->urgency === 'urgent')
                            <span class="badge badge-high">{{ ucfirst($rec->urgency) }}</span>
                        @elseif ($rec->urgency === 'planned')
                            <span class="badge badge-info">{{ ucfirst($rec->urgency) }}</span>
                        @else
                            <span class="badge badge-neutral">{{ ucfirst($rec->urgency ?? 'Pending') }}</span>
                        @endif
                        @if ($rec->risk_level)
                        <span class="text-[11.5px] text-ink-400">Risk: {{ strtoupper($rec->risk_level) }}</span>
                        @endif
                        @if ($rec->target_date)
                        <span class="text-[11.5px] text-ink-400">Target: {{ $rec->target_date->format('M j, Y') }}</span>
                        @endif
                        @if ($rec->requires_human_validation)
                        <span class="text-[10.5px] font-medium text-moderate-700 dark:text-[#d4a830] bg-moderate-50 dark:bg-moderate-50/10 border border-moderate-100 dark:border-moderate-700/30 rounded-md px-1.5 py-0.5">
                            Requires validation
                        </span>
                        @endif
                    </div>

                    @if ($rec->notes)
                    <p class="text-[11.5px] text-ink-400 mt-1 italic">{{ $rec->notes }}</p>
                    @endif
                </div>
                <form method="POST" action="{{ route('recommendations.status', $rec) }}" class="flex-shrink-0">
                    @csrf @method('PATCH')
                    <select name="status" onchange="this.form.submit()" class="form-select w-auto text-[12px] py-1">
                        @foreach (['pending','in_progress','completed','dismissed'] as $s)
                            <option value="{{ $s }}" {{ $rec->status===$s?'selected':'' }}>
                                {{ ucwords(str_replace('_',' ',$s)) }}
                            </option>
                        @endforeach
                    </select>
                </form>
            </div>
            @endforeach
        </div>
    </div>
    @empty
    <x-card>
        <x-empty-state
            icon="document"
            title="No recommendations yet"
            description="Complete a QoL survey and run the ML assessment to generate tailored recommendations.">
            <x-slot name="action">
                <a href="{{ route('surveys.qol.create', $senior) }}" class="btn btn-primary inline-flex gap-1.5">
                    <x-heroicon-o-clipboard-document-list class="w-3.5 h-3.5" /> Take QoL Survey
                </a>
            </x-slot>
        </x-empty-state>
    </x-card>
    @endforelse
</div>
@endsection
