@extends('layouts.app')
@section('page-title', 'Recommendations')
@section('page-subtitle', $senior->full_name . ' · ' . $senior->barangay)

@section('content')
<div class="space-y-5">
    <x-breadcrumb :links="[
        ['label' => 'Dashboard', 'href' => route('dashboard')],
        ['label' => 'Senior Records', 'href' => route('seniors.index')],
        ['label' => $senior->full_name, 'href' => route('seniors.show', $senior)],
        ['label' => 'Recommendations'],
    ]" />
    <x-page-header
        eyebrow="Recommendations"
        :title="$senior->full_name"
        :subtitle="$senior->barangay . ' · ' . $recommendations->count() . ' recommendation' . ($recommendations->count() !== 1 ? 's' : '')"
    />
    <div class="flex items-center gap-3">
        <a href="{{ route('recommendations.index') }}" class="btn btn-ghost gap-1.5 pl-1.5">
            <x-heroicon-o-arrow-left class="w-3.5 h-3.5" /> Recommendations list
        </a>
        <a href="{{ route('seniors.show', $senior) }}" class="btn btn-ghost gap-1.5">
            <x-heroicon-o-user class="w-3.5 h-3.5" /> Back to profile
        </a>
    </div>

    {{-- Critical-priority banner (CRITICAL handled as HIGH with critical_priority_flag) --}}
    @if ($senior->latestMlResult?->critical_flag)
    <div class="flex items-start gap-3 bg-high-50 dark:bg-high-50/10 border border-high-100 dark:border-high-700/30 rounded-xl px-4 py-3">
        <x-heroicon-o-exclamation-triangle class="w-4 h-4 text-high-600 dark:text-high-400 flex-shrink-0 mt-0.5" />
        <p class="text-[12px] text-high-700 dark:text-high-300">
            <strong>Critical-priority flag.</strong> This senior's indicators reached the critical threshold. The risk level is reported as <strong>HIGH</strong> under the 3-level system, with a critical-priority flag for immediate OSCA/RHU/MSWDO coordination.
        </p>
    </div>
    @endif

    {{-- Decision-support disclaimer --}}
    <div class="flex items-start gap-3 bg-info-50 dark:bg-info-50/10 border border-info-100 dark:border-info-700/30 rounded-xl px-4 py-3">
        <x-heroicon-o-information-circle class="w-4 h-4 text-info-600 dark:text-info-400 flex-shrink-0 mt-0.5" />
        <p class="text-[12px] text-info-700 dark:text-info-300">
            <strong>Decision-support output.</strong> These recommendations are generated by the AgeSense analytical model based on WHO Healthy Ageing indicators. They are intended to assist OSCA staff, not replace professional assessment or clinical judgment.
        </p>
    </div>

    {{-- At-a-glance triage: what actually needs doing for this senior --}}
    @if ($recommendations->isNotEmpty())
    @php
        $immCount  = $recommendations->whereIn('urgency', ['immediate','urgent'])->where('status','pending')->count();
        $pendCount = $recommendations->where('status','pending')->count();
        $doneCount = $recommendations->whereIn('status', ['completed','dismissed'])->count();
    @endphp
    <div class="flex flex-wrap items-center gap-x-5 gap-y-2 text-[12.5px] text-ink-600 dark:text-[#a9b1aa]">
        <span class="inline-flex items-center gap-1.5">
            <span class="w-2 h-2 rounded-full bg-high-500"></span>
            <strong class="tnum text-ink-900 dark:text-[#e4e1d8]">{{ $immCount }}</strong> immediate / urgent
        </span>
        <span class="inline-flex items-center gap-1.5">
            <span class="w-2 h-2 rounded-full bg-moderate-500"></span>
            <strong class="tnum text-ink-900 dark:text-[#e4e1d8]">{{ $pendCount }}</strong> pending
        </span>
        <span class="inline-flex items-center gap-1.5">
            <span class="w-2 h-2 rounded-full bg-low-500"></span>
            <strong class="tnum text-ink-900 dark:text-[#e4e1d8]">{{ $doneCount }}</strong> completed
        </span>
    </div>
    @endif

    @php
    $grouped = $recommendations->groupBy('category');
    @endphp

    <div x-data="{ cat: 'all' }" class="space-y-5">
    @if ($grouped->isNotEmpty())
    {{-- Category navigation: pick one section instead of scrolling through all --}}
    @php
        $chipBase   = 'px-3 py-1.5 rounded-lg text-[12px] font-medium leading-tight transition-all duration-100 focus:outline-none focus:ring-2 focus:ring-forest-500/30 inline-flex items-center gap-1.5';
        $chipActive = "'bg-white dark:bg-[#202a26] text-accent-700 dark:text-accent-400 font-semibold shadow-sm ring-1 ring-paper-rule dark:ring-[#2b3530]'";
        $chipIdle   = "'text-ink-500 dark:text-[#8a958f] hover:text-ink-900 dark:hover:text-[#c8c4bc] hover:bg-white/60 dark:hover:bg-[#202a26]/60'";
    @endphp
    <div role="tablist" aria-label="Recommendation categories"
         class="flex flex-wrap gap-1 p-1 rounded-xl bg-paper-2 dark:bg-[#171c19] border border-paper-rule dark:border-[#2b3530]">
        <button type="button" role="tab" @click="cat = 'all'"
                :aria-selected="cat === 'all' ? 'true' : 'false'"
                :class="cat === 'all' ? {{ $chipActive }} : {{ $chipIdle }}"
                class="{{ $chipBase }}">
            All <span class="tnum text-[11px] opacity-70">{{ $recommendations->count() }}</span>
        </button>
        @foreach ($grouped as $category => $recs)
        <button type="button" role="tab" @click="cat = '{{ $category }}'"
                :aria-selected="cat === '{{ $category }}' ? 'true' : 'false'"
                :class="cat === '{{ $category }}' ? {{ $chipActive }} : {{ $chipIdle }}"
                class="{{ $chipBase }}">
            <x-dynamic-component :component="\App\Support\RecommendationCategories::icon($category)" class="w-3.5 h-3.5 flex-shrink-0" aria-hidden="true" />
            {{ \App\Support\RecommendationCategories::label($category) }}
            <span class="tnum text-[11px] opacity-70">{{ $recs->count() }}</span>
        </button>
        @endforeach
    </div>
    @endif

    @forelse ($grouped as $category => $recs)
    <div class="card overflow-hidden" x-show="cat === 'all' || cat === '{{ $category }}'" x-cloak>
        <div class="card-head">
            <div class="card-title flex items-center gap-2">
                <x-dynamic-component :component="\App\Support\RecommendationCategories::icon($category)" class="w-4 h-4 text-ink-500 flex-shrink-0" aria-hidden="true" />
                {{ \App\Support\RecommendationCategories::label($category) }}
            </div>
            <span class="badge badge-neutral">{{ $recs->count() }} action{{ $recs->count() !== 1 ? 's' : '' }}</span>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 p-4">
            @foreach ($recs->sortBy('priority') as $rec)
            <div class="rounded-lg border border-paper-rule dark:border-[#2b3530] p-3.5 flex flex-col gap-1.5 hover:border-ink-300 dark:hover:border-[#3d4d46] transition-colors">
                {{-- Priority + recommendation code + WHO domain badges --}}
                <div class="flex items-center gap-1.5 flex-wrap">
                    <span class="flex-shrink-0 w-6 h-6 rounded-md grid place-items-center text-[11px] font-bold
                        {{ match($rec->urgency) {
                            'urgent'  => 'bg-high-100 text-high-700',
                            'planned' => 'bg-info-100 text-info-700',
                            default   => 'bg-paper-2 text-ink-500',
                        } }}">{{ $rec->priority }}</span>
                    @if ($rec->recommendation_code)
                    <span class="inline-block text-[10px] font-mono font-semibold px-1.5 py-0.5 rounded bg-paper-2 text-ink-500">
                        {{ $rec->recommendation_code }}
                    </span>
                    @endif
                    @if ($rec->domain)
                    <span class="inline-block text-[10px] font-medium px-1.5 py-0.5 rounded bg-info-50 dark:bg-info-50/10 text-info-700 dark:text-info-300 border border-info-100 dark:border-info-700/30">
                        {{ $rec->domain }}
                    </span>
                    @endif
                </div>

                <p class="text-[13px] text-ink-800 leading-relaxed">{{ $rec->action }}</p>

                {{-- Trigger summary: what flagged this recommendation --}}
                @if ($rec->trigger_summary)
                <p class="text-[11.5px] text-ink-500 flex items-start gap-1">
                    <x-heroicon-o-bolt class="w-3.5 h-3.5 flex-shrink-0 mt-0.5 text-ink-400" />
                    <span><span class="font-medium text-ink-600">Trigger:</span> {{ $rec->trigger_summary }}</span>
                </p>
                @endif

                {{-- Service provider --}}
                @if ($rec->service_provider)
                <p class="text-[11.5px] text-ink-500 flex items-start gap-1">
                    <x-heroicon-o-building-office-2 class="w-3.5 h-3.5 flex-shrink-0 mt-0.5 text-ink-400" />
                    <span>{{ $rec->service_provider }}</span>
                </p>
                @endif

                {{-- Evidence source + APA citation --}}
                @if ($rec->evidence_source)
                <p class="text-[11px] text-ink-400 flex items-start gap-1">
                    <x-heroicon-o-document-text class="w-3 h-3 flex-shrink-0 mt-0.5" />
                    <span class="italic">{{ $rec->evidence_source }}</span>
                    @if ($rec->source_type)
                    <span class="not-italic text-ink-300">· {{ $rec->source_type }}</span>
                    @endif
                </p>
                @endif
                @if ($rec->apa_reference)
                <p class="text-[10.5px] text-ink-400 pl-4 italic">{{ $rec->apa_reference }}</p>
                @endif

                {{-- Urgency / risk / target date row --}}
                <div class="flex items-center gap-2 flex-wrap">
                    @if ($rec->urgency === 'urgent')
                        <span class="badge badge-high">{{ ucfirst($rec->urgency) }}</span>
                    @elseif ($rec->urgency === 'planned')
                        <span class="badge badge-info">{{ ucfirst($rec->urgency) }}</span>
                    @else
                        <span class="badge badge-neutral">{{ ucfirst($rec->urgency ?? 'Pending') }}</span>
                    @endif
                    @if ($rec->risk_level)
                    <span class="text-[11.5px] text-ink-400">Risk: {{ strtoupper($rec->risk_level) }}</span>
                    @endif
                    @if ($rec->target_date)
                    <span class="text-[11.5px] text-ink-400">Target: {{ $rec->target_date->format('M j, Y') }}</span>
                    @endif
                    @if ($rec->requires_human_validation)
                    <span class="text-[10.5px] font-medium text-moderate-700 dark:text-[#d4a830] bg-moderate-50 dark:bg-moderate-50/10 border border-moderate-100 dark:border-moderate-700/30 rounded-md px-1.5 py-0.5">
                        Requires validation
                    </span>
                    @endif
                </div>

                @if ($rec->notes)
                <p class="text-[11.5px] text-ink-400 italic">{{ $rec->notes }}</p>
                @endif

                {{-- Status --}}
                <div class="mt-auto pt-2 border-t border-paper-rule dark:border-[#2b3530]">
                    @can('update', $senior)
                    <form method="POST" action="{{ route('recommendations.status', $rec) }}">
                        @csrf @method('PATCH')
                        <select name="status" onchange="this.form.submit()" class="form-select w-full text-[12px] py-1">
                            @foreach (['pending','in_progress','completed','dismissed'] as $s)
                                <option value="{{ $s }}" {{ $rec->status===$s?'selected':'' }}>
                                    {{ ucwords(str_replace('_',' ',$s)) }}
                                </option>
                            @endforeach
                        </select>
                    </form>
                    @else
                    <span class="badge badge-neutral">{{ ucwords(str_replace('_',' ',$rec->status)) }}</span>
                    @endcan
                </div>
            </div>
            @endforeach
        </div>
    </div>
    @empty
    <x-card>
        <x-empty-state
            icon="document"
            title="No recommendations yet"
            description="Complete a QoL survey and run the ML assessment to generate tailored recommendations.">
            @can('update', $senior)
            <x-slot name="action">
                <a href="{{ route('surveys.qol.create', $senior) }}" class="btn btn-primary inline-flex gap-1.5">
                    <x-heroicon-o-clipboard-document-list class="w-3.5 h-3.5" /> Take QoL Survey
                </a>
            </x-slot>
            @endcan
        </x-empty-state>
    </x-card>
    @endforelse
    </div>
</div>
@endsection
