<section id="responsible-use" class="scroll-mt-20 relative py-24 lg:py-32 bg-navy-900 text-paper overflow-hidden">
    <div class="absolute inset-0 dot-field text-white opacity-[0.035] pointer-events-none" aria-hidden="true"></div>

    <div class="shell relative text-center">
        <div class="reveal-up w-14 h-14 rounded-2xl bg-white/10 mx-auto flex items-center justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-7 h-7 text-accent-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9 9 0 0 0 9-9V6.75L12 3 3 6.75V12a9 9 0 0 0 9 9Z"/>
            </svg>
        </div>

        <h2 class="reveal-up font-serif text-[32px] sm:text-[46px] font-semibold tracking-snug leading-[1.12] text-balance mt-7 max-w-3xl mx-auto">
            Technology Supports the Decision.<br>People Make the Decision.
        </h2>

        <div class="reveal-up mt-16 grid sm:grid-cols-3 gap-8 lg:gap-12 max-w-4xl mx-auto text-left">
            @foreach ([
                ['title' => 'Not a Diagnosis', 'body' => 'AgeSense does not diagnose diseases, prescribe treatment, or independently predict clinical outcomes.'],
                ['title' => 'Not Autonomous', 'body' => 'Recommendations do not automatically determine or trigger interventions on their own.'],
                ['title' => 'For Decision Support', 'body' => 'Authorized personnel and appropriate professionals remain responsible for final actions.'],
            ] as $col)
                <div class="border-t border-white/15 pt-5">
                    <div class="text-[11px] font-semibold uppercase tracking-[0.12em] text-accent-300">{{ $col['title'] }}</div>
                    <p class="text-[13.5px] leading-relaxed text-navy-200 mt-2.5">{{ $col['body'] }}</p>
                </div>
            @endforeach
        </div>

        <p class="reveal-up mt-14 text-[12.5px] leading-relaxed text-navy-300 max-w-2xl mx-auto">
            Possible-risk indicators represent study-defined decision-support references and should not be interpreted as independently validated predictions of future clinical outcomes. Recommendations generated by AgeSense require review by authorized personnel or appropriate professionals before any referral, service, program action, or intervention is implemented.
        </p>
    </div>
</section>
