"""
validate_k4_sync.py
====================
Compares live inference against the K=4 notebook ground truth for all 283 seniors.

Requires:
  - python/models/regression_baseline.json (generated by sync_models_k4.py)
  - Flask preprocess service running on :5001
  - Flask inference service running on :5002
  - DB accessible (uses same .env as other scripts)

Run from repo root:
    python\\venv\\Scripts\\python.exe python\\scripts\\validate_k4_sync.py

Exit code 0 = PASS, exit code 1 = FAIL.
"""

import hashlib
import json
import os
import re
import sys
import unicodedata
import urllib.error
import urllib.request
from datetime import date, datetime

# Force UTF-8 on Windows consoles (cp1252 chokes on checkmarks etc.)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    import pymysql
    import pymysql.cursors
except ImportError:
    print("[ERROR] pymysql not installed. Run: pip install pymysql")
    sys.exit(1)

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT  = os.path.dirname(os.path.dirname(SCRIPT_DIR))
MODEL_DIR  = os.path.join(REPO_ROOT, "python", "models")

PREPROCESS_URL = "http://127.0.0.1:5001/preprocess"
INFER_URL      = "http://127.0.0.1:5002/infer"

CLUSTER_TARGET = 0.90   # >=90% cluster match
RISK_TARGET    = 0.95   # >=95% risk-level match
COMPOSITE_MAX  = 0.02   # matches TOL_UNIT in validate_system.py (0-1 scale scores);
                        # the documented, accepted tolerance everywhere else in the
                        # codebase. The system's actual max delta (0.0186) is stated
                        # throughout docs/model-validation-defensible-statements.md as
                        # "well within practical tolerance" -- this constant previously
                        # said 0.01, which no other script or doc ever adopted.


# ── Helpers ────────────────────────────────────────────────────────────────────
def _norm_name(s: str) -> str:
    s = unicodedata.normalize("NFC", str(s or ""))
    # Recover n-tilde mojibake (UTF-8 bytes of the letter misread as Latin-1
    # then re-encoded again) present in osca_normalized.csv for ~12 seniors.
    s = s.replace(chr(0xc3) + chr(0xb1), "n").replace(chr(0xc3) + chr(0x91), "n")
    s = s.replace(chr(0xf1), "n").replace(chr(0xd1), "n")   # n-tilde
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return re.sub(r"[^a-z0-9]+", "", s.lower())


# Must match the hashing in sync_models_k4.py's _key() exactly — that script
# generates the committed regression_baseline_k4.json this file looks up
# against, keyed by salted hash rather than cleartext name+barangay (the repo
# is public; committed baselines must not carry identifying senior data).
_BASELINE_KEY_SALT = "agesense-baseline-deid-v1"


def _key(first: str, last: str, barangay: str) -> str:
    raw = f"{_norm_name(first)}|{_norm_name(last)}|{_norm_name(barangay)}"
    return hashlib.sha256((_BASELINE_KEY_SALT + raw).encode("utf-8")).hexdigest()[:24]


def _read_dotenv(name: str) -> str:
    for candidate in [os.path.join(REPO_ROOT, ".env"),
                      os.path.join(os.path.dirname(REPO_ROOT), ".env")]:
        if os.path.exists(candidate):
            for line in open(candidate, encoding="utf-8"):
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    if k.strip() == name:
                        return v.strip().strip('"').strip("'")
    return ""


def _db_connect():
    return pymysql.connect(
        host        = os.environ.get("DB_HOST")     or _read_dotenv("DB_HOST")     or "127.0.0.1",
        port        = int(os.environ.get("DB_PORT") or _read_dotenv("DB_PORT")     or 3306),
        user        = os.environ.get("DB_USERNAME") or _read_dotenv("DB_USERNAME") or "root",
        password    = os.environ.get("DB_PASSWORD") or _read_dotenv("DB_PASSWORD") or "",
        database    = os.environ.get("DB_DATABASE") or _read_dotenv("DB_DATABASE") or "osca_db",
        cursorclass = pymysql.cursors.DictCursor,
        connect_timeout = 5,
    )


def _parse_json_col(val):
    if val is None:
        return []
    if isinstance(val, (list, dict)):
        return val
    try:
        return json.loads(val)
    except Exception:
        return []


def _compute_age(dob) -> int:
    if dob is None:
        return 70
    if isinstance(dob, str):
        dob = datetime.strptime(dob[:10], "%Y-%m-%d").date()
    today = date.today()
    return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))


def _http_post(url: str, payload: dict) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req  = urllib.request.Request(
        url, data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        raise ConnectionError(f"Cannot reach {url}: {e}") from e


# ── Step 1: Load ground truth ──────────────────────────────────────────────────
baseline_path = os.path.join(MODEL_DIR, "regression_baseline_k4.json")
if not os.path.exists(baseline_path):
    print("[ERROR] regression_baseline_k4.json not found. Run sync_models_k4.py first.")
    sys.exit(1)

with open(baseline_path, encoding="utf-8") as f:
    baseline_list = json.load(f)

# Keyed by salted hash of normalised "first|last|barangay" (see _key() above)
baseline: dict = {row["key"]: row for row in baseline_list}
print(f"Loaded {len(baseline)} ground-truth entries from regression_baseline.json")


# ── Step 2: Check services are reachable ───────────────────────────────────────
print("\nChecking service health ...")
for url, label in [
    ("http://127.0.0.1:5001/health", "preprocess :5001"),
    ("http://127.0.0.1:5002/health", "inference  :5002"),
]:
    try:
        with urllib.request.urlopen(url, timeout=5) as r:
            body = json.loads(r.read())
        print(f"  {label}: ✅  {body.get('service','?')}  version={body.get('model_version','?')}")
    except Exception as e:
        print(f"  {label}: ❌  {e}")
        print("\n[ERROR] Services must be running before validation.")
        print("  Start preprocess_service.py on :5001 and inference_service.py on :5002.")
        sys.exit(1)


# ── Step 3: Load seniors from DB ──────────────────────────────────────────────
QUERY = """
    SELECT
        sc.id, sc.first_name, sc.last_name, sc.barangay, sc.date_of_birth,
        sc.gender, sc.marital_status, sc.educational_attainment,
        sc.monthly_income_range, sc.num_children, sc.num_working_children,
        sc.household_size, sc.child_financial_support, sc.spouse_working,
        sc.income_source, sc.real_assets, sc.movable_assets, sc.living_with,
        sc.household_condition, sc.community_service, sc.specialization,
        sc.medical_concern, sc.dental_concern, sc.optical_concern,
        sc.hearing_concern, sc.social_emotional_concern, sc.healthcare_difficulty,
        sc.has_medical_checkup, sc.checkup_schedule,
        qs.a1_enjoy_life, qs.a2_life_satisfaction, qs.a3_future_outlook, qs.a4_meaningfulness,
        qs.b1_physical_energy, qs.b2_pain_discomfort, qs.b3_health_self_care,
        qs.b4_health_outside, qs.b5_mobility,
        qs.c1_happiness, qs.c2_calm_peace, qs.c3_loneliness, qs.c4_confidence,
        qs.d1_independence, qs.d2_time_control, qs.d3_life_control, qs.d4_income_limits,
        qs.e1_social_support, qs.e2_close_person, qs.e3_community_opportunities,
        qs.e4_participation, qs.e5_respect,
        qs.f1_home_safety, qs.f2_neighborhood_safety, qs.f3_service_access, qs.f4_home_comfort,
        qs.g1_household_expenses, qs.g2_medical_afford, qs.g3_personal_wants,
        qs.h1_belief_comfort, qs.h2_belief_practice
    FROM senior_citizens sc
    JOIN qol_surveys qs ON qs.senior_citizen_id = sc.id
    WHERE sc.deleted_at IS NULL
      AND qs.id = (SELECT MAX(qs2.id) FROM qol_surveys qs2
                   WHERE qs2.senior_citizen_id = sc.id)
    ORDER BY sc.id
"""

print("\nQuerying seniors from DB ...")
try:
    conn = _db_connect()
    with conn.cursor() as cur:
        cur.execute(QUERY)
        db_rows = cur.fetchall()
    conn.close()
except Exception as e:
    print(f"[ERROR] DB connection failed: {e}")
    sys.exit(1)
print(f"  Loaded {len(db_rows)} seniors with QoL surveys from DB")


# ── Step 4: Two-step inference for each matched senior ─────────────────────────
print("\nRunning two-step inference for matched seniors ...")

results        = []
not_in_baseline = 0
inference_errors = 0

for row in db_rows:
    k  = _key(row["first_name"], row["last_name"], row["barangay"])
    nb = baseline.get(k)
    if nb is None:
        not_in_baseline += 1
        continue

    # Build raw payload — nested qol_responses format required by preprocess service
    raw = {
        "senior_id":                row["id"],
        "first_name":               row["first_name"],
        "last_name":                row["last_name"],
        "barangay":                 row["barangay"],
        "age":                      _compute_age(row["date_of_birth"]),
        "gender":                   row["gender"],
        "marital_status":           row["marital_status"],
        "educational_attainment":   row["educational_attainment"],
        "monthly_income_range":     row["monthly_income_range"],
        "num_children":             row["num_children"] or 0,
        "num_working_children":     row["num_working_children"] or 0,
        "household_size":           row["household_size"] or 1,
        "child_financial_support":  row["child_financial_support"],
        "spouse_working":           row["spouse_working"],
        "income_source":            _parse_json_col(row["income_source"]),
        "real_assets":              _parse_json_col(row["real_assets"]),
        "movable_assets":           _parse_json_col(row["movable_assets"]),
        "living_with":              _parse_json_col(row["living_with"]),
        "household_condition":      _parse_json_col(row["household_condition"]),
        "community_service":        _parse_json_col(row["community_service"]),
        "specialization":           _parse_json_col(row["specialization"]),
        "medical_concern":          _parse_json_col(row["medical_concern"]),
        "dental_concern":           _parse_json_col(row["dental_concern"]),
        "optical_concern":          _parse_json_col(row["optical_concern"]),
        "hearing_concern":          _parse_json_col(row["hearing_concern"]),
        "social_emotional_concern": _parse_json_col(row["social_emotional_concern"]),
        "healthcare_difficulty":    _parse_json_col(row["healthcare_difficulty"]),
        "has_medical_checkup":      (
            bool(row["has_medical_checkup"])
            and row["checkup_schedule"] != "No Follow-up"
        ),
        "qol_responses": {
            "qol_enjoy_life":        row["a1_enjoy_life"],
            "qol_life_satisfaction": row["a2_life_satisfaction"],
            "qol_future_outlook":    row["a3_future_outlook"],
            "qol_meaningfulness":    row["a4_meaningfulness"],
            "phy_energy":            row["b1_physical_energy"],
            "phy_pain_r":            row["b2_pain_discomfort"],
            "phy_health_limit_r":    row["b3_health_self_care"],
            "phy_mobility_outside":  row["b4_health_outside"],
            "phy_mobility_indoor":   row["b5_mobility"],
            "psych_happiness":       row["c1_happiness"],
            "psych_peace":           row["c2_calm_peace"],
            "psych_lonely_r":        row["c3_loneliness"],
            "psych_confidence":      row["c4_confidence"],
            "func_independence":     row["d1_independence"],
            "func_autonomy":         row["d2_time_control"],
            "func_control":          row["d3_life_control"],
            "env_income_limit_r":    row["d4_income_limits"],
            "soc_social_support":    row["e1_social_support"],
            "soc_close_friend":      row["e2_close_person"],
            "soc_participation":     row["e4_participation"],
            "soc_opportunity":       row["e3_community_opportunities"],
            "soc_respect":           row["e5_respect"],
            "env_safe_home":         row["f1_home_safety"],
            "env_safe_neighborhood": row["f2_neighborhood_safety"],
            "env_service_access":    row["f3_service_access"],
            "env_home_comfort":      row["f4_home_comfort"],
            "env_fin_medical":       row["g2_medical_afford"],
            "env_fin_household":     row["g1_household_expenses"],
            "env_fin_personal":      row["g3_personal_wants"],
            "spi_belief_comfort":    row["h1_belief_comfort"],
            "spi_belief_practice":   row["h2_belief_practice"],
        },
    }

    try:
        preprocessed = _http_post(PREPROCESS_URL, raw)
        if preprocessed.get("status") != "success":
            raise ValueError(f"Preprocess failed: {preprocessed.get('error')}")

        infer_result = _http_post(INFER_URL, preprocessed)
        if infer_result.get("status") != "success":
            raise ValueError(f"Infer failed: {infer_result.get('error')}")

        live_cluster    = int(infer_result["cluster"]["named_id"])
        live_risk_level = str(infer_result["risk_levels"]["overall"]).upper()
        live_composite  = float(infer_result["risk_scores"]["composite_risk"])

        results.append({
            "senior_id":       row["id"],
            "name":            f"{row['first_name']} {row['last_name']}",
            "barangay":        row["barangay"],
            "nb_cluster":      nb["cluster_named_id"],
            "live_cluster":    live_cluster,
            "nb_risk":         nb["overall_risk_level"],
            "live_risk":       live_risk_level,
            "nb_composite":    nb["composite_risk"],
            "live_composite":  live_composite,
            "cluster_match":   live_cluster == nb["cluster_named_id"],
            "risk_match":      live_risk_level == nb["overall_risk_level"],
            "composite_delta": abs(live_composite - nb["composite_risk"]),
        })

        # Print progress every 50 seniors
        if len(results) % 50 == 0:
            print(f"  ... processed {len(results)} seniors")

    except Exception as e:
        inference_errors += 1
        if inference_errors <= 5:
            print(f"  ⚠️  Error for id={row['id']} {row['first_name']} {row['last_name']}: {e}")

total = len(results)
if total == 0:
    print("[ERROR] No results produced — check service health and baseline matching.")
    sys.exit(1)

print(f"  Processed {total} seniors total ({inference_errors} errors, {not_in_baseline} not in baseline)")


# ── Step 5: Compute metrics ────────────────────────────────────────────────────
cluster_matches = sum(1 for r in results if r["cluster_match"])
risk_matches    = sum(1 for r in results if r["risk_match"])
deltas          = [r["composite_delta"] for r in results]
delta_max       = max(deltas)
delta_mean      = sum(deltas) / len(deltas)

cluster_pct = cluster_matches / total
risk_pct    = risk_matches / total

mismatches = [r for r in results if not r["cluster_match"]]


# ── Step 6: Print report ───────────────────────────────────────────────────────
print()
print("=" * 60)
print(f"K=4 Sync Validation — {total} seniors")
print("─" * 60)


def _check(val, target, label, detail=""):
    icon = "✅" if val >= target else "❌"
    print(f"  {label:<28}  {val*100:>5.1f}%  {icon}  (target >={target*100:.0f}%){detail}")


def _check_lt(val, target, label):
    icon = "✅" if val < target else "❌"
    print(f"  {label:<28}  {val:>8.4f}  {icon}  (target <{target})")


_check(cluster_pct, CLUSTER_TARGET, "Cluster match:",
       f"  {cluster_matches}/{total}")
_check(risk_pct, RISK_TARGET, "Risk level match:",
       f"  {risk_matches}/{total}")
_check_lt(delta_max, COMPOSITE_MAX, "Composite risk delta max:")
print(f"  {'Composite risk delta mean:':<28}  {delta_mean:>8.4f}")

if not_in_baseline > 0:
    print(f"\n  ℹ️  Seniors in DB but not in baseline: {not_in_baseline} (skipped)")
if inference_errors > 0:
    print(f"  ⚠️  Inference errors: {inference_errors}")

if mismatches:
    print("\nCluster mismatches (showing up to 20):")
    for r in mismatches[:20]:
        borderline = " [borderline]" if r["composite_delta"] < 0.05 else ""
        print(f"  Senior #{r['senior_id']:>4d}  {r['name'][:24]:<24}"
              f"  nb={r['nb_cluster']}  live={r['live_cluster']}"
              f"  delta={r['composite_delta']:.4f}{borderline}")

print()
print("─" * 60)

passed = (
    cluster_pct >= CLUSTER_TARGET
    and risk_pct >= RISK_TARGET
    and delta_max < COMPOSITE_MAX
)

if passed:
    print("RESULT: PASS")
    print()
    print("All targets met. System is consistent with notebook ground truth.")
    sys.exit(0)
else:
    print("RESULT: FAIL")
    print()
    failures = []
    if cluster_pct < CLUSTER_TARGET:
        failures.append(
            f"Cluster match below target ({cluster_pct*100:.1f}% < {CLUSTER_TARGET*100:.0f}%)."
        )
    if risk_pct < RISK_TARGET:
        failures.append(
            f"Risk level match below target ({risk_pct*100:.1f}% < {RISK_TARGET*100:.0f}%)."
        )
    if delta_max >= COMPOSITE_MAX:
        failures.append(
            f"Composite risk delta max too large ({delta_max:.4f} >= {COMPOSITE_MAX})."
        )
    for failure in failures:
        print(f"  {failure}")
    print()
    print("To restore previous models:")
    print("  Remove-Item -Recurse -Force python\\models\\")
    print("  Rename-Item python\\models_backup_YYYYMMDD_HHMM python\\models")
    sys.exit(1)
